In [15]:
import numpy as np

In [16]:
X = np.array(([2,9],[1,5],[3,6]), dtype=float)
Y = np.array(([92],[86],[89]))


In [17]:
Z = np.amax(X,axis=0)
X = X/np.amax(X,axis=0)
Y = Y/100

In [18]:
print(X)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]


In [19]:
print(Y)

[[0.92]
 [0.86]
 [0.89]]


In [20]:
epoch = 5000
lr = 0.1
inputlayer_neurons = 2
hiddenlayer_neurons = 3
output_neurons = 1

In [21]:
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

In [22]:
print(wh)

[[0.96818295 0.90703869 0.40711402]
 [0.29972959 0.48381944 0.01029137]]


In [23]:
print(bh)

[[0.59786619 0.0924291  0.91764687]]


In [24]:
print(wout)

[[0.94404061]
 [0.25955672]
 [0.19369787]]


In [25]:
print(bout)

[[0.30224108]]


In [26]:
def sigmoid(X):
    return 1/(1+np.exp(-X))

def derivatives_sigmoid(X):
    return X * (1-X)

In [27]:
for i in range(epoch):
    hinpl=np.dot(X,wh)
    hinp=hinpl+bh
    hlayer_act=sigmoid(hinp)
    outinpl=np.dot(hlayer_act,wout)
    outinp=outinpl+bout
    output=sigmoid(outinp)
    E0=Y-output
    outgrad=derivatives_sigmoid(output)
    d_output= E0*outgrad
    EH=d_output.dot(wout.T)
    hiddengrad=derivatives_sigmoid(hlayer_act)
    d_hiddenlayer=EH*hiddengrad
    wout+=hlayer_act.T.dot(d_output)*lr
    wh+=X.T.dot(d_hiddenlayer)*lr

In [28]:
print('Input: \n' + str(X))
print('Actual output: \n' + str(Y))
print('Predicted output: \n' + str(output))

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted output: 
[[0.89418763]
 [0.87632704]
 [0.89909433]]
